# Generated by Django 5.2.4 on 2025-08-02 15:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('course_code', models.CharField(help_text='e.g., GCCT-M101', max_length=20, unique=True)),
                ('credits', models.IntegerField(default=2)),
                ('month_number', models.IntegerField()),
                ('description', models.TextField()),
                ('learning_objectives', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='faculties.facultyprogram')),
            ],
            options={
                'ordering': ['faculty_program', 'month_number'],
                'unique_together': {('faculty_program', 'month_number')},
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('theme', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('scripture_quote', models.TextField(blank=True, help_text='For faith-based faculties')),
                ('thought_quote', models.TextField(blank=True, help_text='For non-faith-based faculties')),
                ('content', models.TextField()),
                ('resources', models.TextField(blank=True, help_text='Additional resources and readings')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='courses.module')),
            ],
            options={
                'ordering': ['module', 'week_number'],
                'unique_together': {('module', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
                ('max_points', models.IntegerField(default=100)),
                ('due_date_offset', models.IntegerField(default=7, help_text='Days from week start')),
                ('submission_format', models.CharField(default='PDF/Word Document', max_length=100)),
                ('is_required', models.BooleanField(default=True)),
                ('week', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='courses.week')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.FileField(upload_to='assignment_submissions/')),
                ('text_submission', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.assignment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_assignments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('assignment', 'student')},
            },
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.week')),
            ],
            options={
                'unique_together': {('student', 'module', 'week')},
            },
        ),
    ]
