# Generated by Django 5.2.4 on 2025-08-02 15:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level_type', models.CharField(choices=[('masterclass', 'Masterclass (6 months)'), ('diploma', 'Diploma (12 months)'), ('higher_diploma', 'Higher Diploma (12 months)')], max_length=20)),
                ('duration_months', models.IntegerField()),
                ('credits_required', models.IntegerField()),
                ('description', models.TextField()),
                ('prerequisites', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('faculty_type', models.CharField(choices=[('church_theological', 'Church & Theological Education and Transformation'), ('missional_leadership', 'Missional Leadership'), ('sdgs_community', 'SDGs & Community Transformation'), ('education_sustainable', 'Education for Sustainable Development & Global Citizenship'), ('global_leadership', 'Global Leadership & Diplomacy'), ('entrepreneurship', 'Entrepreneurship & Political Economics'), ('climate_warriors', 'Climate Warriors (Environmental Leadership & Action)')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('pillar_focus', models.TextField(help_text='Main pillar and value focus')),
                ('image', models.ImageField(blank=True, null=True, upload_to='faculty_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='FacultyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_structure', models.TextField(help_text='Detailed program structure')),
                ('table_of_contents', models.FileField(blank=True, null=True, upload_to='program_toc/')),
                ('is_active', models.BooleanField(default=True)),
                ('academic_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculties.academiclevel')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='faculties.faculty')),
            ],
            options={
                'unique_together': {('faculty', 'academic_level')},
            },
        ),
    ]
