# Generated by Django 4.2.23 on 2025-08-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="institution",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="town",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
