# Generated by Django 5.2.4 on 2025-08-02 15:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise_areas', models.TextField(help_text='Areas of expertise and specialization')),
                ('years_experience', models.IntegerField()),
                ('max_mentees', models.IntegerField(default=5)),
                ('current_mentees_count', models.IntegerField(default=0)),
                ('bio', models.TextField()),
                ('linkedin_profile', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MentorshipPairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated')], default='pending', max_length=20)),
                ('paired_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('pairing_method', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], default='auto', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorships', to='students.studentenrollment')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorships', to='mentorship.mentorprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('mentor', 'student', 'enrollment')},
            },
        ),
        migrations.CreateModel(
            name='MentorshipMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='mentorship_messages/')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pairing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mentorship.mentorshippairing')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='PeerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_quality', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rate content quality (1-5)')),
                ('creativity', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rate creativity (1-5)')),
                ('presentation', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rate presentation (1-5)')),
                ('feedback', models.TextField(help_text='Constructive feedback')),
                ('suggestions', models.TextField(blank=True, help_text='Suggestions for improvement')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('assignment_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews', to='courses.assignmentsubmission')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('assignment_submission', 'reviewer')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_ending', models.DateField()),
                ('progress_summary', models.TextField(help_text='What did you accomplish this week?')),
                ('challenges_faced', models.TextField(help_text='What challenges did you face?')),
                ('goals_next_week', models.TextField(help_text='What are your goals for next week?')),
                ('mentor_support_needed', models.TextField(blank=True, help_text='What support do you need from your mentor?')),
                ('mood_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rate your mood (1-5)')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mentor_response', models.TextField(blank=True)),
                ('mentor_responded_at', models.DateTimeField(blank=True, null=True)),
                ('pairing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='mentorship.mentorshippairing')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_ending'],
                'unique_together': {('pairing', 'week_ending')},
            },
        ),
    ]
