# Generated by Django 4.2.23 on 2025-09-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="show_correct_answers",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="assignment",
            name="shuffle_questions",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="is_quiz",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="time_limit_minutes",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
