# Generated by Django 4.2.23 on 2025-09-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="moduleprogress",
            options={"ordering": ["program_module__sequence_order"]},
        ),
        migrations.AlterModelOptions(
            name="programmodule",
            options={
                "ordering": ["sequence_order", "module__id"],
                "verbose_name": "Program Module",
                "verbose_name_plural": "Program Modules",
            },
        ),
        migrations.AddField(
            model_name="moduleprogress",
            name="is_unlocked",
            field=models.BooleanField(
                default=False,
                help_text="Whether this module is accessible to the student",
            ),
        ),
        migrations.AddField(
            model_name="moduleprogress",
            name="unlocked_at",
            field=models.DateTimeField(
                blank=True, help_text="When this module was unlocked", null=True
            ),
        ),
        migrations.AddField(
            model_name="programmodule",
            name="minimum_completion_percentage",
            field=models.IntegerField(
                default=80,
                help_text="Minimum completion % required to unlock next module",
            ),
        ),
        migrations.AddField(
            model_name="programmodule",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True,
                help_text="Modules that must be completed before this one",
                to="courses.programmodule",
            ),
        ),
        migrations.AddField(
            model_name="programmodule",
            name="sequence_order",
            field=models.IntegerField(
                default=1,
                help_text="Order in which modules should be completed (1, 2, 3, etc.)",
            ),
        ),
    ]
