# Generated by Django 4.2.23 on 2025-08-10 13:54

import courses.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Brief description of the resource"
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("pdf", "PDF Document"),
                            ("document", "Document"),
                            ("link", "External Link"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Upload video or document files",
                        null=True,
                        upload_to=courses.models.weekly_resource_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "mp4",
                                    "avi",
                                    "mov",
                                    "wmv",
                                    "flv",
                                    "webm",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="External link to resource (YouTube, Vimeo, etc.)",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True, help_text="Duration for video resources", null=True
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="Is this resource required for completion?",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order within the week"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_resources",
                        to="courses.week",
                    ),
                ),
            ],
            options={
                "ordering": ["week", "order", "created_at"],
                "unique_together": {("week", "order")},
            },
        ),
    ]
