# Generated by Django 4.2.23 on 2025-09-27 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_assignment_show_correct_answers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lessonresource",
            name="description",
        ),
        migrations.RemoveField(
            model_name="lessonresource",
            name="title",
        ),
    ]
