# Generated by Django 4.2.23 on 2025-09-27 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_remove_lessonresource_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lessonresource",
            name="estimated_duration_minutes",
        ),
        migrations.RemoveField(
            model_name="lessonresource",
            name="resource_type",
        ),
    ]
