# Generated by Django 4.2.23 on 2025-09-14 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0002_programmodule_sequence_order"),
        ("courses", "0003_lesson_lessonresource_assignment_resourceprogress_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="programmodule",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="programmodule",
            name="module",
        ),
        migrations.RemoveField(
            model_name="programmodule",
            name="prerequisites",
        ),
        migrations.RemoveField(
            model_name="programmodule",
            name="program_level",
        ),
        migrations.AlterUniqueTogether(
            name="studentenrollment",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="studentenrollment",
            name="program_level",
        ),
        migrations.RemoveField(
            model_name="studentenrollment",
            name="student",
        ),
        migrations.AlterModelOptions(
            name="moduleprogress",
            options={"ordering": ["program_module__id"]},
        ),
        migrations.AlterField(
            model_name="course",
            name="program_module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="programs.programmodule",
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="module_type",
            field=models.CharField(
                choices=[
                    (
                        "young_theologians",
                        "Module 1: Young Theologians and Gospel Advancing",
                    ),
                    ("missional_leadership", "Module 2: Missional Leadership"),
                    ("sdgs_community", "Module 3: SDGs & Community Transformation"),
                    (
                        "education_sustainable",
                        "Module 4: Education for Sustainable Development & Global Citizenship",
                    ),
                    (
                        "entrepreneurship",
                        "Module 5: Entrepreneurship and Political Economics",
                    ),
                    ("diplomacy", "Module 6: Diplomacy & Global Leadership"),
                    ("climate_warriors", "Module 7: Climate Warriors"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="moduleprogress",
            name="program_module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="programs.programmodule"
            ),
        ),
        migrations.AlterField(
            model_name="moduletopic",
            name="program_module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="programs.programmodule",
            ),
        ),
        migrations.DeleteModel(
            name="ProgramLevel",
        ),
        migrations.DeleteModel(
            name="ProgramModule",
        ),
        migrations.DeleteModel(
            name="StudentEnrollment",
        ),
    ]
