# Generated by Django 4.2.23 on 2025-10-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_remove_lessonresource_estimated_duration_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="moduleprogress",
            name="completion_percentage",
            field=models.FloatField(
                default=0.0,
                help_text="Alias for progress_percentage for template compatibility",
            ),
        ),
    ]
