# Generated by Django 4.2.23 on 2025-09-04 00:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "module_type",
                    models.CharField(
                        choices=[
                            (
                                "young_theologians",
                                "Module 1: Young Theologians and Gospel Advancing",
                            ),
                            ("missional_leadership", "Module 2: Missional Leadership"),
                            (
                                "sdgs_community",
                                "Module 3: SDGs & Community Transformation",
                            ),
                            (
                                "education_sustainable",
                                "Module 4: Education for Sustainable Development & Global Citizenship",
                            ),
                            (
                                "entrepreneurship",
                                "Module 5: Entrepreneurship and Political Economics",
                            ),
                            ("diplomacy", "Module 6: Diplomacy & Global Leadership"),
                            ("climate_warriors", "Module 7: Climate Warriors"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "learning_objectives",
                    models.TextField(help_text="Key learning objectives"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="module_images/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Module",
                "verbose_name_plural": "Modules",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ProgramLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "level_type",
                    models.CharField(
                        choices=[
                            ("certificate", "Certificate Level"),
                            ("diploma", "Diploma Level"),
                            ("advanced_diploma", "Advanced Diploma Level"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("description", models.TextField()),
                ("duration_months", models.IntegerField()),
                (
                    "focus_areas",
                    models.TextField(help_text="Key focus areas for this level"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Program Level",
                "verbose_name_plural": "Program Levels",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ProgramModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "depth_level",
                    models.CharField(
                        choices=[
                            ("foundational", "Foundational"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=20,
                    ),
                ),
                ("credits", models.IntegerField()),
                (
                    "description",
                    models.TextField(
                        help_text="How this module is taught at this level"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="programs.module",
                    ),
                ),
                (
                    "program_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="programs.programlevel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program Module",
                "verbose_name_plural": "Program Modules",
                "unique_together": {("program_level", "module")},
            },
        ),
    ]
