# Generated by Django 4.2.23 on 2025-09-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmodule",
            name="sequence_order",
            field=models.IntegerField(default=1),
        ),
    ]
