# Generated by Django 4.2.23 on 2025-09-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0002_programmodule_sequence_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmodule",
            name="minimum_completion_percentage",
            field=models.FloatField(
                default=80.0,
                help_text="Minimum percentage required to complete this module",
            ),
        ),
    ]
